# Generated by Django 3.0.4 on 2020-03-29 01:26

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.CharField(max_length=140)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('project_city', models.CharField(max_length=30)),
                ('need_funding', models.BooleanField(default=False)),
                ('funding_type', models.CharField(max_length=30)),
                ('funding_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('ytlink', models.URLField()),
                ('need', models.IntegerField()),
                ('received', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
        ),
    ]
