# Generated by Django 3.0.4 on 2020-04-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200330_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='funding_type',
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
