# Generated by Django 3.0.4 on 2020-03-28 12:23

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200325_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project Name', models.CharField(max_length=30)),
                ('Project Description', models.CharField(max_length=30)),
                ('Contact Name', models.TextField()),
                ('Contact Email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('City', models.CharField(max_length=30)),
                ('Need Funding', models.BooleanField(default=False)),
                ('Enter a funding type (ex: Patreon) ', models.CharField(max_length=30)),
                ('How much funding do you need?', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='recieved',
            new_name='received',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
        ),
    ]
